### ISSUE TITLE
Syntax in Form1

### ISSUE THREAD

**Issue by MrAliSalehi** [RezaParsian/Youtube-Downloader#1]
aval az hame bgm ke projcetato khyli dos drm karet khyli khobe Dude <3 👍 
inja ye moshgli to form 1 hast ke mn ntonstm bfhmm moshgel chie ,va in ke solution ndsht sourcet dahanemon servis shod aqaaaaa,
error:
`CS0117	'Task' does not contain a definition for 'run' `
code : 
`info = await Task.run(() => { return GetVideoInfo(info_url + v_param); });`
va moshgel 2 : 
`result = HttpUtility.UrlDecode(info);`
error:
`The name 'HttpUtility' does not exist in the current context`

**Comment by RezaParsian** [comment]
@mohamadjoker  salam haji.
gaide shodam ba in **finglish** type kardanet 👍 
![Tested](https://user-images.githubusercontent.com/46934941/103154882-270e5900-47b0-11eb-816c-978841a0aba4.png)
